export const actionReduction1Data = [
  {
    type: "select",
    name: "5f60a1676ff16",
    options: [
      { text: "0", value: 0 },
      { text: "1", value: 1 },
      { text: "2", value: 2 },
      { text: "3", value: 3 },
      { text: "4", value: 4 },
      { text: "5", value: 5 },
      { text: "6", value: 6 },
      { text: "7", value: 7 },
      { text: "8", value: 8 },
      { text: "9", value: 9 },
    ],
    firstText: "Prolonger la durée de vie de ses voitures de",
    questionName: "5f55692a73b55",
  },
  {
    type: "select",
    name: "5f60a1760597b",
    options: [
      { text: "0", value: 0 },
      { text: "1", value: 1 },
      { text: "2", value: 2 },
      { text: "3", value: 3 },
      { text: "4", value: 4 },
      { text: "5", value: 5 },
      { text: "6", value: 6 },
      { text: "7", value: 7 },
      { text: "8", value: 8 },
      { text: "9", value: 9 },
    ],
    firstText: "Prolonger la durée de vie de son ordinateur fixe de",
    questionName: "5f5569587abe3",
  },
  {
    type: "select",
    name: "5f7ef2e5cfc27",
    options: [
      { text: "0", value: 0 },
      { text: "1", value: 1 },
      { text: "2", value: 2 },
      { text: "3", value: 3 },
      { text: "4", value: 4 },
      { text: "5", value: 5 },
      { text: "6", value: 6 },
      { text: "7", value: 7 },
      { text: "8", value: 8 },
      { text: "9", value: 9 },
    ],
    firstText: "Prolonger la durée de vie de son ordinateur portable de",
    questionName: "5f55697f50057",
  },
  {
    type: "select",
    name: "5f7ef314bc87c",
    options: [
      { text: "0", value: 0 },
      { text: "1", value: 1 },
      { text: "2", value: 2 },
      { text: "3", value: 3 },
      { text: "4", value: 4 },
      { text: "5", value: 5 },
      { text: "6", value: 6 },
      { text: "7", value: 7 },
      { text: "8", value: 8 },
      { text: "9", value: 9 },
    ],
    firstText: "Prolonger la durée de vie de ses Smartphones de",
  },
  {
    type: "select",
    name: "5f7ef33245f27",
    options: [
      { text: "0", value: 0 },
      { text: "1", value: 1 },
      { text: "2", value: 2 },
      { text: "3", value: 3 },
      { text: "4", value: 4 },
      { text: "5", value: 5 },
      { text: "6", value: 6 },
      { text: "7", value: 7 },
      { text: "8", value: 8 },
      { text: "9", value: 9 },
    ],
    firstText: "Prolonger la durée de vie de ses tablettes de",
    questionName: "5f556b3b7aeaf",
  },
  {
    type: "select",
    name: "5f7ef357156a3",
    options: [
      { text: "0", value: 0 },
      { text: "1", value: 1 },
      { text: "2", value: 2 },
      { text: "3", value: 3 },
      { text: "4", value: 4 },
      { text: "5", value: 5 },
      { text: "6", value: 6 },
      { text: "7", value: 7 },
      { text: "8", value: 8 },
      { text: "9", value: 9 },
    ],
    firstText: "Prolonger la durée de vie des petits bien électroniques de",
    questionName: "5f556b6cefd5a",
  },
];

export const actionReduction2Data = [
  {
    type: "select",
    name: "5f60a199c4870",
    options: [
      { text: "0", value: 0 },
      { text: "1", value: 1 },
      { text: "2", value: 2 },
      { text: "3", value: 3 },
      { text: "4", value: 4 },
      { text: "5", value: 5 },
      { text: "6", value: 6 },
      { text: "7", value: 7 },
      { text: "8", value: 8 },
      { text: "9", value: 9 },
    ],
    firstText: "Remplacer",
    secondText: "paires neuves par des paires de seconde main",
    questionName: "5f556baea779b",
  },
  {
    type: "select",
    name: "5f60a186aee7d",
    options: [
      { text: "0", value: 0 },
      { text: "1", value: 1 },
      { text: "2", value: 2 },
      { text: "3", value: 3 },
      { text: "4", value: 4 },
      { text: "5", value: 5 },
      { text: "6", value: 6 },
      { text: "7", value: 7 },
      { text: "8", value: 8 },
      { text: "9", value: 9 },
    ],
    firstText: "Remplacer",
    secondText: "articles neufs par des articles de seconde main",
    questionName: "5f556b94d465c",
  },
];
